# Imports and defs for lecture

In [2]:
# These are the standard imports for CS 111. 
# This list may change as the quarter goes on.

import os
import math
import time
import struct
import json
import pandas as pd
import networkx as nx
import numpy as np
import numpy.linalg as npla
import scipy
import scipy.sparse.linalg as spla
from scipy import sparse
from scipy import linalg
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d
%matplotlib tk


# Lecture starts here

In [3]:
# Load example E matrix per reading/lecture - all ready saved for you in the .npy file!
E = np.load('PageRankEG1.npy')
E

array([[0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 1.],
       [1., 1., 0., 0.]])

In [4]:
# Calculate the outdegree for each node: col sum
# Use np.sum() for 0th dimension (the row in this square matrix)
outdegree = np.sum(E,0)
outdegree

array([3., 2., 1., 2.])

In [5]:
# Calculate the indegree for each node: row sum
# Use np.sum() for 1st dimension (the column in this square matrix)
indegree = np.sum(E,1)
indegree

array([2., 1., 3., 2.])

In [6]:
# Recall: .shape returns the matrix dimensions
n = E.shape[0]
n

4

In [7]:
# Calculate the eigenvalues vector (d) and the eigenvectors (V)
d, V = linalg.eig(E)

In [8]:
d, V

(array([ 1.94978752+0.j        , -0.74540166+0.74952824j,
        -0.74540166-0.74952824j, -0.45898421+0.j        ]),
 array([[ 0.55529338+0.j        , -0.61105409+0.j        ,
         -0.61105409-0.j        ,  0.21563856+0.j        ],
        [ 0.28479687+0.j        ,  0.40761959+0.40987619j,
          0.40761959-0.40987619j, -0.46981694+0.j        ],
        [ 0.65184165+0.j        ,  0.04484216-0.32104126j,
          0.04484216+0.32104126j, -0.65275928+0.j        ],
        [ 0.43086246+0.j        ,  0.41063857-0.13696104j,
          0.41063857+0.13696104j,  0.55378459+0.j        ]]))

In [9]:
# Recall:
print(E)
print()
print(outdegree)

[[0. 0. 1. 1.]
 [1. 0. 0. 0.]
 [1. 1. 0. 1.]
 [1. 1. 0. 0.]]

[3. 2. 1. 2.]


In [10]:
# Calculate the Link Matrix A from E:
A = E / outdegree
A

array([[0.        , 0.        , 1.        , 0.5       ],
       [0.33333333, 0.        , 0.        , 0.        ],
       [0.33333333, 0.5       , 0.        , 0.5       ],
       [0.33333333, 0.5       , 0.        , 0.        ]])

### *We now need to find the eigenvector for eigenvalue = 1*

In [19]:
A = np.array([[0,0,1,0.5],[1/3,0,0,0],[1/3,0.5,0,0.5],[1/3,0.5,0,0]])
print(A)


[[0.         0.         1.         0.5       ]
 [0.33333333 0.         0.         0.        ]
 [0.33333333 0.5        0.         0.5       ]
 [0.33333333 0.5        0.         0.        ]]


In [8]:
# Start by finding the eigenVs of A:
d, V = linalg.eig(A)
print(d)
print()
print(V)

[ 1.        +0.j         -0.36062333+0.41097555j -0.36062333-0.41097555j
 -0.27875333+0.j        ]

[[ 0.72101012+0.j          0.75521571+0.j          0.75521571-0.j
   0.50648562+0.j        ]
 [ 0.24033671+0.j         -0.3036721 -0.34607247j -0.3036721 +0.34607247j
  -0.60565568+0.j        ]
 [ 0.54075759+0.j         -0.09315321+0.2746779j  -0.09315321-0.2746779j
  -0.38153917+0.j        ]
 [ 0.36050506+0.j         -0.3583904 +0.07139457j -0.3583904 -0.07139457j
   0.48070923+0.j        ]]


In [13]:
# Then, let's look at the Real values of V (of eigenvector 0) - which matches the eigenvalue = 1
# This is a clean-up effort as the complex numbers here are actually real (imaginary parts are ~0)
v = V[:,0].real
print(v)
print(npla.norm(v))
print(v/npla.norm(v))

[0.72101012 0.24033671 0.54075759 0.36050506]
1.0
[0.72101012 0.24033671 0.54075759 0.36050506]


In [28]:

B = A - np.eye(4)
print(B)
b = np.array([[0,0,0,0]])
print(b)
print(npla.solve(B,b.T))


[[-1.          0.          1.          0.5       ]
 [ 0.33333333 -1.          0.          0.        ]
 [ 0.33333333  0.5        -1.          0.5       ]
 [ 0.33333333  0.5         0.         -1.        ]]
[[0 0 0 0]]
[[-0.]
 [-0.]
 [-0.]
 [-0.]]


In [18]:
A = np.array([[0,1/2,1/2,0,1/4],[1/3,0,0,0,1/4],[1/3,0,0,0,1/4],[0,0,0,0,1/4],[1/3,1/2,1/2,1,0]])
print(A)
# Start by finding the eigenVs of A:
d, V = linalg.eig(A)
print(d)
print()
print(V)
# Then, let's look at the Real values of V (of eigenvector 0) - which matches the eigenvalue = 1
# This is a clean-up effort as the complex numbers here are actually real (imaginary parts are ~0)
v = V[:,0].real
print(v)
print(npla.norm(v))
print(v/npla.norm(v))

[[0.         0.5        0.5        0.         0.25      ]
 [0.33333333 0.         0.         0.         0.25      ]
 [0.33333333 0.         0.         0.         0.25      ]
 [0.         0.         0.         0.         0.25      ]
 [0.33333333 0.5        0.5        1.         0.        ]]
[ 1.00000000e+00+0.j -7.28713554e-01+0.j -5.00000000e-01+0.j
  2.28713554e-01+0.j -2.03548374e-17+0.j]

[[ 5.14495755e-01  2.60425827e-01 -7.50000000e-01 -5.54236762e-01
  -2.33952125e-17]
 [ 3.42997170e-01 -3.79551660e-01  2.50000000e-01 -2.53522919e-01
  -7.07106781e-01]
 [ 3.42997170e-01 -3.79551660e-01  2.50000000e-01 -2.53522919e-01
   7.07106781e-01]
 [ 1.71498585e-01 -2.60425827e-01 -2.50000000e-01  5.54236762e-01
   3.64931686e-17]
 [ 6.85994341e-01  7.59103321e-01  5.00000000e-01  5.07045838e-01
   8.16370951e-17]]
[0.51449576 0.34299717 0.34299717 0.17149859 0.68599434]
1.0
[0.51449576 0.34299717 0.34299717 0.17149859 0.68599434]


In [6]:
eig_perm = np.argsort(v)
print("The order of our eigenvector's INDICES sorted ascending:   ", eig_perm)
eig_perm = np.argsort(v)[::-1]
print("The order of our eigenvector's INDICES sorted descsending: ", eig_perm)

The order of our eigenvector's INDICES sorted ascending:    [1 3 2 0]
The order of our eigenvector's INDICES sorted descsending:  [0 2 3 1]


### *Sanity-checks*

In [ ]:
# Double-check we got the eigenvector v right:
# A v should be equal to eigenvalue * v = v (since eigenvalue = 1)
print(A @ v)

In [ ]:
# Double-check we did the Link Matrix correctly:
# It's supposed to be a column stochastic matrix, i.e. columns must add up to 1
print(np.sum(A,0))

### *Let's create a situation with a "dangling node"*

In [ ]:
E

In [ ]:
# Make node/page "1" lose connection to page "3"
E[0,2] = 0
print(E)

In [ ]:
# When we try to calculate the Link Matrix...
A = E / np.sum(E,0)
print(A)

In [ ]:
# When we try further to find the EVs of A...
print(linalg.eig(A))