# Imports and defs for lecture

In [1]:
# These are the standard imports for CS 111. 
# This list may change as the quarter goes on.

import math
import numpy as np
import numpy.linalg as npla

# New one!
import struct

# Lecture starts here

### *The peculiarities of inf and nan in Python (numpy vs. math vs. standard)*

In [2]:
np.log(1)

0.0

In [3]:
np.log(0)

C:\Users\jayle\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [4]:
np.log(-1)
#no way for numpy express a negative/ complex number

C:\Users\jayle\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

In [5]:
np.sqrt(9)

3.0

In [6]:
np.sqrt(-9)
# it is complex number, it does have solution, but in the numpy world, it doesnt have a solution 

C:\Users\jayle\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [10]:
math.sqrt(-9)

ValueError: math domain error

In [8]:
(-9)**0.5
#raised to the power works tho, basic python, and it does have a solution that is represented in imaginary
#real plus imaginary

(1.8369701987210297e-16+3j)

In [9]:
np.isnan([np.log(-1.), 1., np.log(0), np.sqrt(-9), (-9)**0.5])
#returns if it is not a number or not.

C:\Users\jayle\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.
C:\Users\jayle\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
C:\Users\jayle\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([ True, False, False,  True, False])

### *Eigenvalues and Eigenvectors Demo*

In [11]:
#A = np.array([[1,1,1],[1,0,2],[2,2,1]])
#np.random.seed(80085)
A = np.random.randn(4,4)
print(A)
npla.matrix_rank(A)

[[ 0.9988399   0.70244041  0.95532894  0.63749826]
 [-0.91958433  0.64827455  2.18478217 -0.477636  ]
 [-0.27154439  0.34524352 -0.06902495  1.97150105]
 [-0.58614279  1.5022517   0.48845966 -0.69344753]]


4

In [12]:
help(npla.eig)
# if you ever forget how to use commands

Help on function eig in module numpy.linalg.linalg:

eig(a)
    Compute the eigenvalues and right eigenvectors of a square array.
    
    Parameters
    ----------
    a : (..., M, M) array
        Matrices for which the eigenvalues and right eigenvectors will
        be computed
    
    Returns
    -------
    w : (..., M) array
        The eigenvalues, each repeated according to its multiplicity.
        The eigenvalues are not necessarily ordered. The resulting
        array will be of complex type, unless the imaginary part is
        zero in which case it will be cast to a real type. When `a`
        is real the resulting eigenvalues will be real (0 imaginary
        part) or occur in conjugate pairs
    
    v : (..., M, M) array
        The normalized (unit "length") eigenvectors, such that the
        column ``v[:,i]`` is the eigenvector corresponding to the
        eigenvalue ``w[i]``.
    
    Raises
    ------
    LinAlgError
        If the eigenvalue computation does not 

In [13]:
d, V = npla.eig(A)
print("d:\n", d, "\n\nV:\n", V)
# Note the possible complex numbers that come up
# d is the eigenvalues returned by the eig function 
# V is the eigen vectors 

d:
 [ 1.52972674+1.00648857j  1.52972674-1.00648857j -1.08740575+1.35535594j
 -1.08740575-1.35535594j] 

V:
 [[-0.75485624+0.j         -0.75485624-0.j          0.01648477+0.02740764j
   0.01648477-0.02740764j]
 [-0.17353939-0.40061537j -0.17353939+0.40061537j  0.63435197+0.j
   0.63435197-0.j        ]
 [-0.22506924-0.30552229j -0.22506924+0.30552229j -0.50794784+0.29610809j
  -0.50794784-0.29610809j]
 [-0.10012106-0.29250506j -0.10012106+0.29250506j -0.05000103-0.49838093j
  -0.05000103+0.49838093j]]


In [14]:
V[:,0]
#0,j means apprx 0 complex

array([-0.75485624+0.j        , -0.17353939-0.40061537j,
       -0.22506924-0.30552229j, -0.10012106-0.29250506j])

In [15]:
# Ax = lambda.x
# works on the columns of A and x as well as on the whole matrices
print(A@V[:,0] - d[0]*V[:,0])
print()
print(A@V[:,2] - d[2]*V[:,2])
print()
print(A@V - d*V)
# d is the eigenvalues returned by the eig function 

[ 6.66133815e-16+5.55111512e-16j  1.94289029e-16+4.44089210e-16j
 -1.38777878e-16+2.22044605e-16j -2.22044605e-16+5.55111512e-16j]

[ 9.02056208e-17-9.71445147e-16j -5.55111512e-16-2.22044605e-16j
 -1.11022302e-15+6.66133815e-16j  5.55111512e-16-3.88578059e-16j]

[[ 8.88178420e-16+5.55111512e-16j  8.88178420e-16-5.55111512e-16j
   1.87350135e-16-8.95984675e-16j  1.87350135e-16+8.95984675e-16j]
 [ 2.22044605e-16+4.44089210e-16j  2.22044605e-16-4.44089210e-16j
  -5.55111512e-16-2.22044605e-16j -5.55111512e-16+2.22044605e-16j]
 [-1.04083409e-16+3.33066907e-16j -1.04083409e-16-3.33066907e-16j
  -1.08246745e-15+6.66133815e-16j -1.08246745e-15-6.66133815e-16j]
 [-1.94289029e-16+6.66133815e-16j -1.94289029e-16-6.66133815e-16j
   6.66133815e-16-4.44089210e-16j  6.66133815e-16+4.44089210e-16j]]


In [16]:
print(npla.norm(A@V[:,0] - d[0]*V[:,0]))
print()
print(npla.norm(A@V[:,2] - d[2]*V[:,2]))
print()
print(npla.norm(A@V - d*V))
#expect theses to be very close to zero, which they are

1.1886388043482663e-15

1.8560082022393165e-15

3.2858907067161524e-15


In [17]:
# Let's find the transpose of A:
print("A:\n", A, "\n\nA.T\n", A.T)

A:
 [[ 0.9988399   0.70244041  0.95532894  0.63749826]
 [-0.91958433  0.64827455  2.18478217 -0.477636  ]
 [-0.27154439  0.34524352 -0.06902495  1.97150105]
 [-0.58614279  1.5022517   0.48845966 -0.69344753]] 

A.T
 [[ 0.9988399  -0.91958433 -0.27154439 -0.58614279]
 [ 0.70244041  0.64827455  0.34524352  1.5022517 ]
 [ 0.95532894  2.18478217 -0.06902495  0.48845966]
 [ 0.63749826 -0.477636    1.97150105 -0.69344753]]


In [18]:
# ... and let's find A.T's eigenvalues and eigenvectors:
dt, Vt = npla.eig(A.T)
print("dT:\n", dt, "\n\nd:\n", d, "\n\nVT:\n", Vt)

dT:
 [ 1.52972674+1.00648857j  1.52972674-1.00648857j -1.08740575+1.35535594j
 -1.08740575-1.35535594j] 

d:
 [ 1.52972674+1.00648857j  1.52972674-1.00648857j -1.08740575+1.35535594j
 -1.08740575-1.35535594j] 

VT:
 [[-0.64869853+0.j         -0.64869853-0.j          0.05548281-0.05324021j
   0.05548281+0.05324021j]
 [ 0.22749916+0.39549813j  0.22749916-0.39549813j -0.34048953-0.33054783j
  -0.34048953+0.33054783j]
 [ 0.25184277+0.46662787j  0.25184277-0.46662787j -0.24468855+0.43343004j
  -0.24468855-0.43343004j]
 [ 0.11395577+0.27724233j  0.11395577-0.27724233j  0.72191278+0.j
   0.72191278-0.j        ]]


In [19]:
# Find the difference between d and dt
print(d - dt)
print()
print(npla.norm(d - dt))

[ 8.8817842e-16-2.22044605e-16j  8.8817842e-16+2.22044605e-16j
 -8.8817842e-16-2.22044605e-16j -8.8817842e-16+2.22044605e-16j]

1.831026719408895e-15


In [20]:
# Find the difference between V and Vt
print(V - Vt)
print()
print(npla.norm(V - Vt))

[[-0.10615771+0.j         -0.10615771+0.j         -0.03899804+0.08064785j
  -0.03899804-0.08064785j]
 [-0.40103855-0.7961135j  -0.40103855+0.7961135j   0.9748415 +0.33054783j
   0.9748415 -0.33054783j]
 [-0.47691201-0.77215016j -0.47691201+0.77215016j -0.26325929-0.13732195j
  -0.26325929+0.13732195j]
 [-0.21407683-0.56974739j -0.21407683+0.56974739j -0.77191382-0.49838093j
  -0.77191382+0.49838093j]]

2.8284271247461903


In [21]:
# What do we notice about matrix B?
B = A + A.T
B

array([[ 1.99767981, -0.21714392,  0.68378455,  0.05135547],
       [-0.21714392,  1.2965491 ,  2.53002569,  1.02461571],
       [ 0.68378455,  2.53002569, -0.1380499 ,  2.45996071],
       [ 0.05135547,  1.02461571,  2.45996071, -1.38689505]])

In [22]:
# Prove B is symmetrical!
B - B.T

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# Let's find B's eigenvalues and eigenvectors:
dB, VB = npla.eig(B)
print("dB:\n", dB, "\n\nVT:\n", VB)

# What do you notice about these values????

dB:
 [ 4.24716273  2.06459248 -3.50322433 -1.03924694] 

VT:
 [[-0.13470493  0.97652449  0.08739342 -0.14358582]
 [-0.66163184 -0.21158481  0.21820489 -0.68546466]
 [-0.62367411  0.03036845 -0.68552036  0.37439312]
 [-0.39386355 -0.02663722  0.6890652   0.60774263]]


In [24]:
# Test out the A = X.LAMBDA.X-1 property:
# X is the eigenvectors
# LAMBDA is the eigenvalues placed as diagonals in a matrix
print("A:\n", A)
print()
LAMBDA = np.diag(d)
print("LAMBDA:\n", LAMBDA)
print()
M = (V@LAMBDA)@(npla.inv(V))
print("X LAMBDA X-1:\n", M)
print()
print(npla.norm(M - A))

A:
 [[ 0.9988399   0.70244041  0.95532894  0.63749826]
 [-0.91958433  0.64827455  2.18478217 -0.477636  ]
 [-0.27154439  0.34524352 -0.06902495  1.97150105]
 [-0.58614279  1.5022517   0.48845966 -0.69344753]]

LAMBDA:
 [[ 1.52972674+1.00648857j  0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          1.52972674-1.00648857j  0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j         -1.08740575+1.35535594j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  -1.08740575-1.35535594j]]

X LAMBDA X-1:
 [[ 0.9988399 -4.04072974e-17j  0.70244041+7.02674276e-17j
   0.95532894+1.72776412e-16j  0.63749826-1.68479874e-16j]
 [-0.91958433+3.90698718e-17j  0.64827455+2.00685776e-16j
   2.18478217-3.96035003e-17j -0.477636  -2.28729831e-16j]
 [-0.27154439-4.52437378e-17j  0.34524352-4.59300816e-18j
  -0.06902495+6.81446896e-17j  1.97150105-1.40542420e-16j]
 [-0.58614279+4.46437434e-17j  1.