<em>We'll start off by importing numpy and the linear algebra class (linalg) from numpy</em>

In [1]:
import numpy as np
import numpy.linalg as npla

***Cholesky Example***

In [6]:
C = np.array([[5, 5, 5],[5,6,5],[5,5,8]])
print("C:\n", C,"\n\nC.T:\n",C.T,"\n")
L = npla.cholesky(C)
print("L:\n",L,"\n")
print("L@LT:\n", L @ L.T)

x = np.array([-11,55,10])
print("\nxT@C@x:\n", x.T@C@x)

C:
 [[5 5 5]
 [5 6 5]
 [5 5 8]] 

C.T:
 [[5 5 5]
 [5 6 5]
 [5 5 8]] 

L:
 [[ 2.23606798e+00  0.00000000e+00  0.00000000e+00]
 [ 2.23606798e+00  1.00000000e+00  0.00000000e+00]
 [ 2.23606798e+00 -4.85863154e-16  1.73205081e+00]] 

L@LT:
 [[5. 5. 5.]
 [5. 6. 5.]
 [5. 5. 8.]]

xT@C@x:
 17905


***Finding Eigenvalues***

*Note: npla.eig(C)[0] gives you the eigenvalues, [1] gives you the eigenvectors*

In [7]:
lambdas = npla.eig(C)
print(lambdas[0])

[16.43991452  0.42793012  2.13215536]


In [8]:
lambdas = npla.eig(np.array([[2,1],[1,2]]))
print(lambdas[0])

[3. 1.]


***QR Factorization Examples***

In [9]:
A = np.array([[1,2],[3,4]])
Q, R = npla.qr(A)
print("Q:\n", Q,"\nR:\n", R, "\nQ@R:\n", Q@R)

Q:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]] 
R:
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]] 
Q@R:
 [[1. 2.]
 [3. 4.]]


In [10]:
A = np.array([[1,2,4],[0,0,5],[0,3,6]])
Q, R = npla.qr(A, mode='reduced')
print("Q:\n", Q,"\nR:\n", R, "\nQ@R:\n", Q@R)

Q:
 [[ 1.  0.  0.]
 [-0.  0. -1.]
 [-0. -1.  0.]] 
R:
 [[ 1.  2.  4.]
 [ 0. -3. -6.]
 [ 0.  0. -5.]] 
Q@R:
 [[1. 2. 4.]
 [0. 0. 5.]
 [0. 3. 6.]]


***Examples of stability in matrices***

In [11]:
A = np.array([[1,1000],[0,1]])
b1 = np.array([0,1])
x1 = npla.solve(A,b1)

x2 = np.array([-999.999, 1.001])

print("x1:", x1, "\nx2:", x2)
print("\nA @ x1:", A@x1)
print("A @ x2:", A@x2)
print("\nresidual norm:", npla.norm(b1 - A@x2))
print("\ncondition number of A:\n",npla.cond(A))

x1: [-1000.     1.] 
x2: [-999.999    1.001]

A @ x1: [0. 1.]
A @ x2: [1.001 1.001]

residual norm: 1.0010004995002375

condition number of A:
 1000001.9999990001


In [12]:
A = np.array([[1,9],[9,1]])
b1 = np.array([9,1])
x1 = npla.solve(A,b1)

x2 = np.array([0.001, 0.999])

print("x1:", x1, "\nx2:", x2)
print("\nA @ x1:", A@x1)
print("A @ x2:", A@x2)
print("\nresidual norm:", npla.norm(b1 - A@x2))
print("\ncondition number of A:\n",npla.cond(A))

x1: [0. 1.] 
x2: [0.001 0.999]

A @ x1: [9. 1.]
A @ x2: [8.992 1.008]

residual norm: 0.011313708498985399

condition number of A:
 1.2499999999999998


In [13]:
A = np.array([[1,1,0],[1,0,1],[0,1,1]])
b1 = np.array([1,2,1])
x1 = npla.solve(A,b1)

x2 = np.array([1.1,0.1,1])

print("x1:", x1, "\nx2:", x2)
print("\nA @ x1:", A@x1)
print("A @ x2:", A@x2)
print("\nresidual norm:", npla.norm(b1 - A@x2))
print("\ncondition number of A:\n",npla.cond(A))

x1: [ 1. -0.  1.] 
x2: [1.1 0.1 1. ]

A @ x1: [1. 2. 1.]
A @ x2: [1.2 2.1 1.1]

residual norm: 0.24494897427831802

condition number of A:
 2.0000000000000004
